initial Commit

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -334,79 +334,75 @@ jobs:
       - revert-migrations        
                     
   deploy-backend:
+    deploy-backend:
     docker:
-      - image: cimg/base:stable
+      - image: python:3.7-alpine3.11
+        environment:
+          NODE_ENV: "local"
+          VERSION: "1"
+          ENVIRONMENT: "production"
+          TYPEORM_CONNECTION: $TYPEORM_CONNECTION
+          TYPEORM_HOST: $TYPEORM_HOST
+          TYPEORM_USERNAME: $TYPEORM_USERNAME
+          TYPEORM_PASSWORD: $TYPEORM_PASSWORD
+          TYPEORM_DATABASE: $TYPEORM_DATABASE
+          TYPEORM_PORT: $TYPEORM_PORT
+          TYPEORM_ENTITIES: $TYPEORM_ENTITIES
     steps:
       - checkout
-      
       - add_ssh_keys:
-          fingerprints:
-            - "d5:5d:93:4f:51:e7:cc:7e:a5:d0:90:7c:6b:64:7d:b5"
+          fingerprints: ["d5:5d:93:4f:51:e7:cc:7e:a5:d0:90:7c:6b:64:7d:b5"]
       - attach_workspace:
-          at: ~/  
-      - install_awscli
-      - install_ansible 
-      
-      - install_nodejs     
-     
-
-      # - run:
-      #     name: Package Backend
-      #     command: |
-      #       cd backend
-      #       npm run build
-      #       tar -czf artifact.tar.gz dist/* package*
-
-      #       cd ..
-      #       cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files      
+          at: /root
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update ansible rsync 
+            apk add curl
+            pip3 install awscli
       - run:
           name: Deploy backend
           command: |
-           cd backend
-           npm i
-           npm run build
-           cd ..
-           cd .circleci/ansible
-           mkdir files
-           cd files
-           tar -C ../../../backend -czvf artifact.tar.gz .
-           cd ../
-           echo "Contents of the inventory.txt file is ......."
-           cat inventory.txt
-           ansible-playbook -i inventory.txt deploy-backend.yml
+            ls /root
+            ls /root/project/backend/
+            cat ~/project/.circleci/ansible/inventory.txt
+            ansible-playbook -i ~/project/.circleci/ansible/inventory.txt ~/project/.circleci/ansible/deploy-backend.yml
+      # Here's where you will add some code to rollback on failure
            
 
       - destroy-environment
       - revert-migrations
   smoke-test:
     docker:
-      - image: cimg/base:stable
+      - image: python:3.7-alpine3.11
     steps:
       - checkout
-      - install_nodejs
-      - install_awscli
-      # - install_ansible 
-        
-      # Checkout code from git
+      - attach_workspace:
+          at: /root
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update curl
+            pip install awscli
       
-      # - run:
-      #     name: Backend smoke test.
-      #     command: |
-      #       BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-      #        --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-      #        --query 'Reservations[*].Instances[*].PublicIpAddress' \
-      #        --output text)
-      #       export API_URL="http://${BACKEND_PUBLIC_IP}:3030"
+      - run:
+          name: Backend smoke test.
+          command: |
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+             --query 'Reservations[*].Instances[*].PublicIpAddress' \
+             --output text)
+            export API_URL="http://${BACKEND_PUBLIC_IP}:3030"
             
             
-      #       echo backend-${CIRCLE_WORKFLOW_ID:0:7}
-      #       echo "${API_URL}"
-      #       if curl -s $API_URL/api/status | grep "ok"
-      #       then
-      #           exit 0
-      #       else
-      #           exit 1
-      #       fi   
+            echo backend-${CIRCLE_WORKFLOW_ID:0:7}
+            echo "${API_URL}"
+            if curl -s $API_URL/api/status | grep "ok"
+            then
+                exit 0
+            else
+                exit 1
+            fi   
       - run:
           name: Frontend smoke test.
           command: |
@@ -421,53 +417,51 @@ jobs:
              fi
       # - destroy-environment
       # - revert-migrations     
-#       # Here's where you will add some code to rollback on failure  
+      # Here's where you will add some code to rollback on failure  
 
-#   cloudfront-update:
-#     docker:
-#       - image: amazon/aws-cli
-#     steps:
-#       - checkout
-#       - run:
-#           name: Install dep / Save Old Workflow ID to kvdb.io
-#           command: |
-#             export OldWorkflowID=$(aws cloudformation \
-#              list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-#               --no-paginate --output text)
-#               echo OldWorkflowID: "${OldWorkflowID}"
-#               https://kvdb.io/WdFS6WqDPr7GKdq9KZ6QZi/OldWorkflowID  -d "${OldWorkflowID}"
-              
-          
-    
-#       - run:
-#           name: Update cloudfront distribution
-#           command: |
-#             aws cloudformation deploy \
-#                 --template-file .circleci/files/cloudfront.yml \
-#                 --stack-name InitialStack \
-#                 --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
-#                 --tags project=udapeople
-#       - destroy-environment
-#       - revert-migrations        
+  cloudfront-update:
+     docker:
+      - image: amazon/aws-cli
+     steps:
+      - checkout
+      - run:
+          name: get old workflow for clean
+          command: |
+            WorkflowID=$(aws cloudformation \
+            list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+            --no-paginate --output text)
+            curl -H "Content-Type: text/plain" -H "token: ecdfc255-81e1-4056-9efa-2d7fa10812e1" --request PUT --data "$WorkflowID" https://api.memstash.io/values/workflowid
+      - run:
+          name: Update cloudfront distribution
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/cloudfront.yml \
+              --tags project=circleci-${CIRCLE_WORKFLOW_ID:0:7} \
+              --stack-name "udapeople-cloudfrontstack" \
+              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}"
 
-# cleanup:
-#     docker:
-#       # Docker image here
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Get old stack workflow id
-#           command: |
-#             # your code here
-#             export OldWorkflowID="the id here"
-#             export STACKS=[] #put the list of stacks here
-#       - run:
-#           name: Remove old stacks and files
-#           command: |
-#             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-#             then
-#               # your code here
-#             fi
+cleanup:
+   docker:
+      - image: amazon/aws-cli
+   steps:
+      - checkout
+      - run:
+          name: Remove old stacks and files
+          command: |
+            OLD_WORKFLOW_ID=$(curl -H "token: ecdfc255-81e1-4056-9efa-2d7fa10812e1" --request GET https://api.memstash.io/values/workflowid)
+            CurrentWorkflowID=${CIRCLE_WORKFLOW_ID:0:7}
+            if [[ $OLD_WORKFLOW_ID == "" ]]
+            then
+            echo "No workflow id found"
+            else
+            if [[ "$CurrentWorkflowID" != "$OLD_WORKFLOW_ID" ]]
+            then
+              echo "$OLD_WORKFLOW_ID!=$CurrentWorkflowID => will delete old version"
+              aws s3 rm "s3://udapeople-${OLD_WORKFLOW_ID}" --recursive
+              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OLD_WORKFLOW_ID}"
+              aws cloudformation delete-stack --stack-name "udapeople-backend-${OLD_WORKFLOW_ID}"
+            fi
+            fi
             
 
 workflows:
@@ -498,7 +492,7 @@ workflows:
           requires: [run-migrations]
       - smoke-test:
           requires: [deploy-backend, deploy-frontend]
-      # - cloudfront-update:
-      #     requires: [smoke-test]
-      # - cleanup:
-      #     requires: [cloudfront-update]
+      - cloudfront-update:
+          requires: [smoke-test]
+      - cleanup:
+          requires: [cloudfront-update]
